services:
    _defaults:
        autowire: true
        autoconfigure: true

    Tbo\FormDelayProtection\EventListener\FormSpamProtectionListener: ~

    Tbo\FormDelayProtection\Migration\LegacyColumnsToVirtualFieldsMigration: ~
